# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWFkMzBiOTQ3ODgxYjcyZDFiNWJiN2ViMWMwM2VlMjM0MzMzMTA1ZjUwZDBmNTQ0OTM5MjM0YWU4NjhhMDMxMWRmMjBmOWNjY2YwZTQ0OGEwYmYwODhlMWM0ZjYzNzQwZWI0ZjY4YTVhOGU3YTlhNTVhOTRmZmQ0OTkxOWU0OGI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
